### PR TITLE
UV fluctuation model for cross-correlation

### PR DESCRIPTION
**Pull request by mblomqvist**
Add the UV fluctuation model to object-forest cross-correlation fit in fitter2.

### CODE REVIEW

**Comment by mblomqvist** [comment]
Also fixes the bug reported in #409

**Comment by mblomqvist** [comment]
Codacy is complaining about the use of 'assert', but we have many such occurrences in the codes. I assume that we can ignore the complaint.

**Comment by londumas** [comment]
@mblomqvist, yes ignore the complaint for `assert`. Some day we will dive into it.
Thank you for the PR.

**Comment by mblomqvist** [comment]
ready to be merged

**Pull request merged**
