### PR TITLE
Standardisation

### PR DESCRIPTION
**Pull request by iprafols**

### CODE REVIEW

**Comment by londumas** [comment]
@iprafols and @andreufont, let's stop this PR. This is going to bring so many bugs, for no gain. I really do not see the goal of it. Except if you manage to explain why you are doing that, I would suggest to stop. There are not even any description in the PR.
I re;ind to everyone, that the standard way to do a PR is before to write an issue, and discuss it before starting anything.

**Comment by iprafols** [comment]
Hi @londumas,

This branch was created as part of a project I am doing for my computer science degree. 

I find that naming of variables in picca are super confusing. It just complicates the code unnecessarily. Some variables have different meaning in different files. For instace the variable fid stands for 'Fiberid of the object' or for 'Variable to store the list of fiducial parameters' depending on the file it is used. 

I also find that there is a lack of comments and docstrings thrugout the package that could certainly help in following what the code is doing. This would allow newcommers to be able to develop picca more easily. Additionally it would be nice to have picca's workflow explained somewhere.

I created this pull request in order to see if the automatic tests passed, and that is why it don't have any description yet. I don't intend to have it pulled yet. Note that the pull request was to a branch called standardisation that I just created for this purpose, and that I intend more extensive tests to be performed before merging it with master. While I agree that this will potentially create many bugs, I don't agree that it will not be useful.

I wasn't aware that an the policy was to create an issue before creating the pull request. I can create an issue if necessary

Cheers

**Comment by londumas** [comment]
@iprafols, I am sorry but picca is not intended to be part of a computer science degree. It is a package for physicist that want to have a nice code, but who do really care about backward compatibility and not breaking a code that was tested a lot. I would advise you to stop directly this PR, start a ticket with a tread for the picca devs to talk about the use for this standardization.
You can do your changes on your own fork.
I labeled this PR as wontfix.

**Comment by londumas** [comment]
@iprafols, squeeze is a nice place for you computer science project, since it is your own package and I bet it needs a lot of improvements.

**Comment by andreufont** [comment]
Hi @londumas , @iprafols - Let's pause this for a while, and start a calm discussion on an issue. I think it is useful to work towards better documentation of picca, and that some isolated bits could be improved, but we should do this step by step, issue by issue.

**Pull request closed without merging**
