### PR TITLE
Protect i/o for pk1D

### PR DESCRIPTION
**Pull request by Cyeche**

### CODE REVIEW

**Comment by londumas** [comment]
@Cyeche, did you run the tests?

**Comment by mblomqvist** [comment]
The code mixes False and None. Should we make it uniform?

**Comment by Cyeche** [comment]
Yes and it passed the unitest.

**Comment by Cyeche** [comment]
> 
> The code mixes False and None. Should we make it uniform?

The default is None  in do_deltas and I suspect that the test is done over None in many places….

**Comment by mblomqvist** [comment]
Disregard the earlier comment which was immediately deleted.

**Pull request merged**
