### PR TITLE
Fix issue 401

### PR DESCRIPTION
**Pull request by vserret**

### CODE REVIEW

**Comment by londumas** [comment]
@vserret, could you merge with master, correct conflicts and produce again your `*fits.gz` files?
To merge with master:
```
merge master
git push
```

**Comment by vserret** [comment]
@ngbusca ready to be merged

**Comment by ngbusca** [comment]
@vserret you mentioned that this branch made the code significantly slower. Is it the case?

**Comment by vserret** [comment]
No It was the branch named "resolve_issue_399" where I've made changes to avoid absorbers with z > zqso.
In this branch I've just corrected a bug in the computation of the metal dmat.

**Comment by ngbusca** [comment]
Fixed in PR #399

**Pull request closed without merging**
