### PR TITLE
Cast to float64

### PR DESCRIPTION
**Pull request by londumas**
This PR cast to float64 `RA`, `DEC` and `Z` when converting desi data or mocks.
It also add a warning when `cosinus<-1` or `cosinus>1`.
It also removes computing the angle between an object and itself.
I am currently testing it, I tell you @ngbusca when it is ready to be merged.

Fix partly issue https://github.com/igmhub/picca/issues/436

### CODE REVIEW

**Comment by londumas** [comment]
Here is the not-projected cross-correlation variance after and before this PR for the transmission.
There is still some spikes, but way less important.
We removed the majority of the effect.
The remaining spikes could be linked to the computation of the angle when it is small.
We have to dig into this.
This covariance matrix is not positive definite for all before and now, as it can be understood by the big correlation matrix.

capture d ecran de 2018-05-23 18-27-45

capture d ecran de 2018-05-23 18-27-57

**Comment by londumas** [comment]
The current PR don't fix all of the issue, see attached plot for London mocks. Using the random catalog don't produce these spikes. The random catalog was produced in double precision.
Still investigating, I plan do test with a random shuffle of the mock catalog to see if indeed the issue still comes from the precision.

covar

covar_zoom

**Comment by londumas** [comment]
Looking only at r_perp<12 Mpc/h, we can see this issue using the catalog of quasars, but not when using the randoms. This effect is caused by close pairs of delta-quasar, where the quasar is behind
the quasar hosting the delta: r_perp<4 and r_paral<-50.
I have looked and it doesn't seem to be linked to our calculation of the angle.

mockcat_london_smallscales

randomcat_london_smallscales

**Comment by londumas** [comment]
@ngbusca, ready to be merged

**Comment by ngbusca** [comment]
@londumas I don't see the codacy checks. For some reason sometimes they disappear. Let's wait a bit to see if they come back.

**Comment by londumas** [comment]
@ngbusca, Codacy doesn't tell what is wrong when I click on the link.

**Pull request merged**
