### PR TITLE
avoid pairs of pixels from the same qso for forest xcf

### PR DESCRIPTION
**Pull request by vserret**

### CODE REVIEW

**Comment by ngbusca** [comment]
@vserret the `d.ra != d1.ra` condition is not enough?

**Comment by londumas** [comment]
@ngbusca, I asked @vserret to use thingid because it is more stable.
In simulations we can have ra1==ra2 but dec1!=dec2.
Also it make more sens to use thingid than ra

**Comment by ngbusca** [comment]
@londumas I agree it makes more sense, but I was wondering whether this change was a just a matter of principle or there was an actual problem

**Comment by londumas** [comment]
I don't think it introduces a bug now since `ra` is a double not even a float, but in the future it could. Better remove this now than too late.

**Comment by vserret** [comment]
Not a problem, just a matter of principle

**Pull request merged**
