### PR TITLE
Fix issue 258

### PR DESCRIPTION
**Pull request by vserret**

### CODE REVIEW

**Comment by ngbusca** [comment]
what bothers me from this is that the fill_neighs is the coupled to the fiducial cosmology. I'd prefer to keep a pure angle selection even if this results in some lose of performance. I think we should even remove this cut from the xcf.fill_neighs function.

**Comment by londumas** [comment]
@vserret, what is your gain in terms of time?
@ngbusca, why don't you want to couple fill_neighs to the cosmology ? Any way we already suppose flatness.

**Comment by ngbusca** [comment]
@londumas because we might want to do the analysis in observable coordinates where there's no fiducial cosmology.

**Comment by londumas** [comment]
@ngbusca, if we gain a lot from this commit, we could have different version of fill_neight. If we don't gain enough, no need to do anything.

**Comment by ngbusca** [comment]
@londumas yep, as with any optimization!

**Comment by londumas** [comment]
>@londumas yep, as with any optimization!

Agree

**Comment by londumas** [comment]
@vserret, can we remove this PR?

**Comment by vserret** [comment]
yes

**Pull request closed without merging**
