### PR TITLE
Dev pk1 d

### PR DESCRIPTION
**Pull request by Cyeche**
Implementation of the computation of the 1D power spectrum
- Changes in forest and delta (should be transparent for the other modules)
- in picca/bin addition of do_Pk1D which performs the 1D P(k) with a FFT
- Noise computed  either with the pipeline errors or with the difference of the exposure computed by pairs

### CODE REVIEW

**Comment by londumas** [comment]
Hi @Cyeche, could you resolve the conflicts ?
Do you still want to do this merge request ?

**Comment by ngbusca** [comment]
@londumas can you run a few tests on this branch? I'll be hitting the slopes until wednesday (but I'll be able to merge if you ok it)

**Comment by londumas** [comment]
@ngbusca, I can't. I will be observing next week, and I don't know enough of Pk

**Comment by ngbusca** [comment]
@londumas then you'll have plenty of time to run tests! I didn't mean the Pk part (@Cyeche already checked that), it's just want to make sure it doesn't break other parts of the code.

**Comment by ngbusca** [comment]
@Cyeche you changed the constructor of the forest class by adding the diff and reso parameters, but didn't fix all the calls to the forest class. Could you grep "forest(" and make the necessary fixes?

**Comment by ngbusca** [comment]
@Cyeche it might actually be better to default them to None, this way you don't need to change anything else in the code...

**Comment by Cyeche** [comment]
Sorry I have just checked with mode ==« spec"….  It should be fine now…

**Comment by ngbusca** [comment]
@Cyeche there are several instances in the code that break when diff and reso are None, e.g in the constructor of forest, e.g.:

    diff=diff[w]
    reso=reso[w]

or
    
    cdiff = sp.bincount(bins,weights=iv*diff)
    creso = sp.bincount(bins,weights=iv*reso)

etc.

These fields are required only by the Pk1D part of the code, can't they get added later on? I think this will greatly reduce the collisions with other parts of the code... 

Note that you can add fields to a python object on the fly, they don't need to be allocated in the constructor (just do d.diff = ...)

**Comment by Cyeche** [comment]
Hi,

It should be fine now. I checked that I do not break the code when I read pix format. Tell me if I should perform additional test.

**Comment by andreufont** [comment]
@Cyeche - Let me know when this is working, it would be really cool to run P1D on the new DESI mocks!

**Comment by Cyeche** [comment]
In principle, it works. We are just checking that we haven’t broken the rest of the code ;-).

**Comment by ngbusca** [comment]
I've checked that the auto-correlation runs without a problem. The only thing that bothers me a bit is that the fields diff and reso are filled with zeros and ones respectively even though they are not used at all in most of the analyses, but will increase the memory footprint. @Cyeche do we absolutely need to have them set to something? Can't we keep them "None" unless needed? If it doesn't require too many "acrobaties" could you implement that? If it does, I'm ok with leaving things as they are now.

**Comment by Cyeche** [comment]
Actually, I think with None, it doesn’t work. This the reason why diff is not empty.

**Comment by ngbusca** [comment]
@Cyeche We (@londumas ) 've added unit tests to picca, now merged to master. Please merge this branch with the latests master and check that it passes the automatic tests:

    python py/picca/test/test_cor.py

Thanks!

**Comment by ngbusca** [comment]
@nathalieGit @Cyeche there are conflicts with master, can you fix them ?

**Comment by Cyeche** [comment]
This is what I have added last night?

**Comment by ngbusca** [comment]
@Cyeche master didn't change since last night... there are conflicts in three files:

    bin/do_deltas.py
    py/picca/prep_del.py
    py/picca/test/test_cor.py

If you do `git merge master` you will see where the conflict are.

**Comment by Cyeche** [comment]
This is what I don’t understand, I haven't any conflict and everything is up-to-date...

**Comment by ngbusca** [comment]
@Cyeche did you push your changes?

**Comment by Cyeche** [comment]
Yes I did, I even double checked…



git status
On branch Dev_Pk1D
Your branch is up-to-date with 'origin/Dev_Pk1D'.
nothing to commit, working directory clean
sppmcaa34:picca yeche$ git pull
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 5), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (13/13), done.
From https://github.com/igmhub/picca
   8d4c9b4..db049e5  fix_issue_270 -> origin/fix_issue_270
Already up-to-date.
sppmcaa34:picca yeche$ git merge master
Already up-to-date.
sppmcaa34:picca yeche$ git status
On branch Dev_Pk1D
Your branch is up-to-date with 'origin/Dev_Pk1D'.
nothing to commit, working directory clean
sppmcaa34:picca yeche$ git push origin Dev_Pk1D
Everything up-to-date

**Comment by londumas** [comment]
@yeche.
In this page you can see that the master has a conflict with you branch.
A `git pull` will not change this. You have to resolve the conflicts and then do a `git pull`.

**Pull request merged**
