### PR TITLE
add boolean tracer to fitter2

### PR DESCRIPTION
**Pull request by londumas**
Add the list of individual tracers to fitter2. Fix issue https://github.com/igmhub/picca/issues/359.
`tracer` is a very bad name but I don't really have other ideas.
We could also call them `boolean_tracer`. Any idea @mblomqvist and @ngbusca?
@mblomqvist, do you want me to add `SLA` or `LLS`.

This list will serve as a nomenclature as `constants.absorber_IGM` is doing.

### CODE REVIEW

**Comment by ngbusca** [comment]
Don't you think it would be better to leave the names arbitrary but have a tracer type? The way to implement this would be to create a class tracer with two attributes: the name (arbitrary) and the tracer type (collapsed_tracer or absorber_tracer). Then, the Pk or xi functions would receive instances of this class instead of strings, and they would make the assertions on the tracer_type attribute. Makes sense ?

**Comment by ngbusca** [comment]
The user would have to specify in the .ini both the tracer name and the tracer type

**Comment by londumas** [comment]
@ngbusca, I am not sure to understand why would you want a complicated class when a dictionary or a list does the job.

**Comment by ngbusca** [comment]
@londumas My point is that all the code needs to check is whether the tracer is a discrete tracer or not. If the user specifies that the tracer is discrete that's enough, otherwise you will have to add a tracer name to the list every time there's a new tracer (say `QSO_TYPE_X` or `ELG_HIGH_LUMINOSITY`, etc. etc.)

By the way, I prefer discrete tracer to collapsed tracer since the former is agnostic to the physics of the tracer (what if we want to use a discrete tracer that is not a collapsed object? e.g. a catalog of small lyman-alpha absorptions).

Finally, one very simple way out is to remove the assertions and trust the user knows what he's doing.

**Comment by londumas** [comment]
@ngbusca, Thank you for the answer.
I added giving the type of tracers in the `config.ini` file, the issue now is that we have to pass it to `xi.py` and `pk.py` and this would change a lot of things.
An other thing we could do would be to remove the two assert. But this is dangerous.

**Comment by ngbusca** [comment]
@londumas as for how to pass it, I would do a minimal change. All functions receive an argument tracer1 and tracer2, which is currently a string. If we used a dictionary instead of a string that would solve the problem. The dictionary would have a key `name` and a key `type`... what do you think?

**Comment by ngbusca** [comment]
for the assertions, coadacy likes try-except blocks instead, because that works in compiled python, while the asserts are ignored. Since we are not compiling for now, I would leave the asserts and ignore the coadacy suggestion.

**Comment by londumas** [comment]
@ngbusca, I actually just had the same idea of using a dictionary.
It still produces a lot of changes, are you ok with that?

**Comment by ngbusca** [comment]
@londumas yes, I'm ok with that!

**Comment by londumas** [comment]
@ngbusca, ready to be merged. Could you do a review?

**Pull request merged**
