### PR TITLE
Add example config files for reproducing DR16

### PR DESCRIPTION
**Pull request by andreicuceu**
I add example config files for DR16. I haven't tested these in more than a year, so it would be great if there was a volunteer that could do it (e.g. check if the current version of picca still produces the same results as it should). Note that the files as they are include the chi2 scan for completeness. However, the scans take a very long time to run, so to test them we can just run a simple fit.

### CODE REVIEW

**Comment by andreufont** [comment]
Hi @andreicuceu - now that Shuo Yuan has successfully reproduced the results, we could merge this branch. We could mention it tomorrrow at the Picca telecon, and then merge?

**Comment by iprafols** [comment]
Let's do this

**Review by iprafols — APPROVED** [review]
Let's review this PR at the picca task force telecon tomorrow (June 9) before merging, but it is otherwise fine by me

**Comment by andreicuceu** [comment]
Sounds good to me

**Comment by andreicuceu** [comment]
@iprafols, I added the change to .gitignore to this pull request as it should be added to master soon.

**Review by iprafols — APPROVED** [review]

**Comment by iprafols** [comment]
HI @andreicuceu, perfect. Normally we should merge tomorrow after the telecon

**Pull request merged**
