### PR TITLE
One seed per proc

### PR DESCRIPTION
**Pull request by londumas**
This PR allows to have a different seed per processors. Currently, the same seed is used across all processors, and thus the same series of pairs are rejected.
This can cause some small issues.
Since all these branches are being refactored for MP, I didn't implement for do_dmat and do_metal_dmat. The goal is to have a trace of a way to correct this small issue and apply it to MP files once they are merged or even before. This code works for Python2 and Python3, but implies to recreate a lot of test/data/ files.
Correct issue https://github.com/igmhub/picca/issues/417

### CODE REVIEW

**Comment by ngbusca** [comment]
I don't understand this phrase `Currently, the same seed is used across all processors, and thus the same series of pairs are rejected.` What do you mean?

**Comment by londumas** [comment]
What I mean is simple: in the current master, for `do_xdmat.py` for example, we set the seed to `0` (`random.seed(0)`). Then we split the data set, and send the computation on different processors. Each of these will have the seed set to `0`. The result is that the same random number will be used to reject some of the pairs in the computation in `py/picca/xcf.py`. It is never good to use the same randoms. However, normally each pair forest-qso is unique so it shouldn't produce a big difference.
The only case where it could is if the pairs were sorted by the quasar index, which is the case.
Normally this issue shouldn't have a big impact, but "prevention is better than cure".

**Comment by ngbusca** [comment]
I see, I thought that there was only one random state common to all multipocessing child processes, but it's actually not the case. All child process inherit the same random state, so you indeed get the same sequence. 

What I don't like in your solution is that we need to modify the arguments of functions to pass a seed which is annoying and syntactically ugly. I also don't like that the user would set a seed, it's useless  low level control.

Wouldn't it be much simpler if the random generator is initialized with the first healpixel id? e.g.:

    def calc_dmat(p):
        random.seed(p[0])

**Comment by londumas** [comment]
agreed and agreed. Let me do a PR with your idea.

**Comment by londumas** [comment]
re-implemented in https://github.com/igmhub/picca/pull/461.

**Pull request closed without merging**
