### PR TITLE
commented out print_fmin from iminuit, it was crashing

### PR DESCRIPTION
**Pull request by andreufont**
iminuit2 seems to have deprecated this function

### CODE REVIEW

**Comment by andreufont** [comment]
@iprafols , @Waelthus - this should also be propagated to the Everest tag, and update it (not sure how to update a tag...)

**Comment by Waelthus** [comment]
can you check if print(self.fmin) works? We can make this a bugfix tag 4.2.1 and I think there's a way to update the release to the new tag then...

**Review by iprafols — APPROVED** [review]

**Comment by andreufont** [comment]
@Waelthus - working on it!

**Comment by iprafols** [comment]
I'm happy to either comment this print or checking if Michael's sugestion works

**Comment by andreufont** [comment]
@Waelthus - when I try your suggestion, I get the following error:
Minuit' object has no attribute 'print'

Let's merge the pull request as is, and open an issue to solve this properly at another time.

**Comment by Waelthus** [comment]
> @Waelthus - when I try your suggestion, I get the following error: Minuit' object has no attribute 'print'
> 
> Let's merge the pull request as is, and open an issue to solve this properly at another time.

Fine that this was merged, the error seems weird to me, did you do this:
`print(self.best_fit.fmin)`
or this:
`self.best_fit.print(fmin)`
It looks like some iteration of the latter...

**Comment by andreufont** [comment]
I'm not sure what I tried, but it definitely had self.best_fit.print on it.

**Comment by Waelthus** [comment]
ok, then that's the reason it failed, what I meant was the former. So just using the normal print function on the self.best_fit.fmin. The print_xxx functions inside iminuit2 have been removed. As this was failing during analysis, but not in the regression tests, we should probably update those as well.

**Pull request merged**
