### PR TITLE
compute unfold cf 

### PR DESCRIPTION
**Pull request by vserret**
Add modifications in the computation of symmetric cfs such as lya(lya)xlya(lyb). 
Standardly, we compute this cf with rp = abs(rp) 
But we can also have rp positive or negative (depending on the relative position between abs1 and abs2) by adding the "unfold-cf" option

### CODE REVIEW

**Comment by londumas** [comment]
@vserret, looks good. Did you have a look if it worked on data?

**Comment by vserret** [comment]
Yes, it seems to work well

**Comment by vserret** [comment]
@londumas , ready to be merged !

**Comment by londumas** [comment]
@vserret, thank you very much.

**Pull request merged**
