### PR TITLE
correct option name

### PR DESCRIPTION
**Pull request by londumas**
correct option name for `-best-obs`.

### CODE REVIEW

**Comment by ngbusca** [comment]
What is the purpose of `zfill`?

**Comment by londumas** [comment]
`zfill` adds zeros at the beginning if the size of the string is less than a giving number. ex:
```
a = '123'
a.zfill(4)
-> '0123'
```

**Comment by londumas** [comment]
https://www.tutorialspoint.com/python/string_zfill.htm

**Comment by ngbusca** [comment]
Thanks @londumas, I know what `zfill` does and I know how to use google, I am asking why you added it since it seems totally unrelated to "correct option name for -best-obs."

**Comment by londumas** [comment]
Lol, sorry.
I did two corrections in one. I can do another PR if you want.
In order to read the DR7 data, I need to use `--best-obs` because there are no spAll.fits,
and I need to read plates that are less than 4 digits long.

**Comment by ngbusca** [comment]
Ok, I see. No need for another PR, in the future please spend some time explaining what PR is for!

**Comment by londumas** [comment]
@ngbusca, Yes sorry.

**Comment by ngbusca** [comment]
merge when ready @londumas

**Pull request merged**
