### PR TITLE
Apply codacy 4

### PR DESCRIPTION
**Pull request by londumas**
Remove unused variables and correct implementation of checking type

### CODE REVIEW

**Comment by ngbusca** [comment]
@londumas can you take a look at the conflicts?

**Comment by londumas** [comment]
@ngbusca, ready to be merged

**Comment by mblomqvist** [comment]
I'm viewing chi2.py. By replacing 'it' by '_' aren't you breaking the line 198
self.fast_mc_data[d.name+'_'+str(it)] = d.da

**Comment by londumas** [comment]
@mblomqvist, thank you. I did not noticed that `it` was used now.
I just corrected this error.

**Comment by ngbusca** [comment]
Ideally @londumas @mblomqvist this should have been picked up by the automatic tests, is it because we don't test the `fast mc` option? they are already pretty long, should we add a test for the `fast mc` ? what do you think?

**Comment by londumas** [comment]
@ngbusca, The unittest are long simply because of the environment setup.
The rest is reasonable. We can add a unittest for `fast_mc` if you want.

**Comment by mblomqvist** [comment]
I'm considering some more options for the fast MC, so maybe the unit test can wait for those to be implemented first

**Comment by londumas** [comment]
ok, works for me

**Comment by ngbusca** [comment]
> @ngbusca, The unittest are long simply because of the environment setup. The rest is reasonable. We can add a unittest for fast_mc if you want.

This is not true, setting up the environment takes ~5min, the rest takes ~15min.

**Comment by ngbusca** [comment]
> I'm considering some more options for the fast MC, so maybe the unit test can wait for those to be implemented first

no problem, let's open an issue so we don't forget.

**Comment by londumas** [comment]
@ngbusca, ready to be merged.

**Pull request merged**
