### PR TITLE
fix issue 252

### PR DESCRIPTION
**Pull request by londumas**
https://github.com/igmhub/picca/issues/252

Fix issue due to missing neighs

### CODE REVIEW

**Comment by londumas** [comment]
@vserret, could you test it?

**Comment by londumas** [comment]
Cool, thank you @vserret. Did you try with two metals?
Did you try the do_metal_dmat (i.e. for cf)?

**Comment by vserret** [comment]
there is a problem on do_metal_dmat.py
problem with identation level on line 23

**Comment by londumas** [comment]
Thank you for spoting this can you test now that I corrected this error ?

**Comment by vserret** [comment]
this works

**Comment by londumas** [comment]
Thank you @vserret.
@ngbusca, ready to be merged.

**Comment by londumas** [comment]
@ngbusca, I agree with you but for the time being I don't have any idea how to do that differently.

**Pull request merged**
