### PR TITLE
fix reading proper fiberid in spplate

### PR DESCRIPTION
**Pull request by londumas**
Fix issue https://github.com/igmhub/picca/issues/475:
Reading the proper fiberid when using multiple observation of spplates

### CODE REVIEW

**Comment by ngbusca** [comment]
@londumas I see that photoPosPlate seems better than spAll. But your solution assumes that the code is run on an environment where all those files are available. Could you add a check such that if photoPosPlate is not found the code tells the user to run with the `--bestobs` option and exits?

**Comment by londumas** [comment]
@ngbusca, yes this is a good idea. Doing this now.

**Comment by londumas** [comment]
@ngbusca, This fixes reading the proper fiberid in spplate or spcframe.
I had to change the way `str_iexp` was used in spcframe because it is a zfill(3) now in `$BOSS_SPECTRO_REDUX/v5_11_0/`

**Comment by ngbusca** [comment]
@londumas let me know when it's ready for review

**Comment by londumas** [comment]
@ngbusca, ok. I am adding the possibility to use the platequality.txt file.

**Comment by londumas** [comment]
@ngbusca, ready to be reviewd.
This PR also adds a `--platequality` option to `do_deltas.py` that takes a file with a similar
format as platequality.txt of the SDSS pipeline, i.e. at least
```
 PLATE   MJD   QUALITY 
  3520 55071  bad
```
This is useful to remove bad observation when using all observations.

**Comment by londumas** [comment]
@ngbusca, ok. Let me do this.

**Comment by londumas** [comment]
@ngbusca, I corrected your last request.
The last thing we can do is that dome objects are observed on different plate.
Currently we are missing them, a simple solution is to change `wfib` to something like
`sp.in1d(thid,h_photoPlate[1]['THING_ID'][:])`. Does this work for you?

**Comment by londumas** [comment]
@ngbusca, Ready to be attentively reviewed.

**Comment by ngbusca** [comment]
@londumas I have a doubt now, aren't we also losing reobservations that are in plates different from the bestobs?

**Comment by ngbusca** [comment]
I think we should take the time to get this right: if the option `--bestobs` is used then do what we do now. Otherwise: open spAll (discover it from the given plates directory) and get all the plate-mjd-fid for all the given thing_id from it. I think spAll contains only good plates (?). This avoids the files platequality.txt and spPhotoPlate files from being opened. What do you think?

**Comment by londumas** [comment]
@ngbusca, I think that what we currently have corrects the bug for DR14 papers. Let's merge this and work on a refactor for DR16. It is only a vers small fraction of objects that will have a higher SNR.

As far as I have seen of it, spAll is not the file we need, we need a file that I produce for redrock that map thingid to all  observations. I don't think spAll does this. Does it?
It is in `$DESI_WORK/rrboss/SDSS_redrock_archetypes_newDeltaChi2/spplates/map_thingid_targetids_photoPosPlate.fits` for v5_10_10.

By the way, don't use `photoPlate`, use `photoPosPlate`. `photoPlate` is based on luminosity, and doesn't work. `photoPosPlate` is based on the position, and this works.

**Comment by ngbusca** [comment]
@londumas I think this is the best time to fix this once and for all. spAll contains a list of all observations in good plates. So if you select a THING_ID you can get all plate-mjd-fid that correspond to that THING_ID. So I think yes, it has the info that we need. I'm find using your file if it's produced automatically by the pipeline.

**Comment by ngbusca** [comment]
spAll contains a column for THING_ID, which is repeated for all the observations. There's a column SPECPRIMARY which is 1 for the best. I think spAll only contains good plates, so there's no need for platequality.txt (but it wold be good to check that a few bad plates are not in spAll).

**Comment by londumas** [comment]
@ngbusca, why not simply use PLATE_DUPLICATE, MJD_DUPLICATE, FIBERID_DUPLICATE from `$EBOSS_ROOT/qso/DR14Q/DR14Q_v3_1.fits`. This seems so much simpler.

**Comment by ngbusca** [comment]
I don't think that format will be kept for DR16...

**Comment by ngbusca** [comment]
but I would be ok with that being a temporary solution...

**Comment by ngbusca** [comment]
This issue will be fixed in PR #479

**Pull request closed without merging**
