### PR TITLE
Change names of executable

### PR DESCRIPTION
**Pull request by londumas**
Change names of executable, fix issue https://github.com/igmhub/picca/issues/531.
The names are now: `picca_*.py`. I removed the `do` when used and added `*.py` in order for Codacy tu see the file. @ngbusca could you tell me if that is what you had in mind?
I rand `picca_nersc_submit.py` and everything work.

### CODE REVIEW

**Comment by londumas** [comment]
@Waelthus and @Cyeche, are the new names of the executable you use ok?

**Comment by Waelthus** [comment]
I'm fine, just need to change the name in some scripts/notebooks, but that should be easy enough. So it's really just `do_` -> `picca_` and everything in bin that didn't have a `do_` before now has been prepended?

**Comment by londumas** [comment]
@Waelthus, yes and also I added a *.py everywhere to allow Codacy to check all files.

**Comment by londumas** [comment]
@vserret, I hve little time to do that now. What we can do is merge this and add a issue ticket with this idea. Anyway, it has very little effect since it acts only on the decimals. Is that ok for you?

**Comment by vserret** [comment]
> @vserret, I hve little time to do that now. What we can do is merge this and add a issue ticket with this idea. Anyway, it has very little effect since it acts only on the decimals. Is that ok for you?

@londumas I think you did not reply on the good PR. Anyway, you are right. The effect would be very very small. We can keep that for latter.

**Pull request merged**
