### PR TITLE
save iter file at each iteration

### PR DESCRIPTION
**Pull request by Waelthus**
This saves the iter (or delta_attributes) file after each continuum fitting iteration. It also computes the stack after each iteration. If the latter is too expensive we could only do this for the last iteration.

### CODE REVIEW

**Review by iprafols — APPROVED** [review]
changes look fine

**Review by iprafols — CHANGES_REQUESTED** [review]
Why are the tests not passing?

**Comment by Waelthus** [comment]
I'm trying to figure that out. I'm getting a numpy error in the end about a broadcasting (1,100) -> (10,10). Not sure where that comes from in detail yet...

**Comment by Waelthus** [comment]
was an issue where `np.broadcast` was used on `var_pipe_values` and overwrote the array, for all but the last iteration this was replaced in the iteration, but for the last one only mean_cont is computed and the array isn't replaced, which made the broadcast fail on this. Now I just generate a new variable for writing this output

**Review by iprafols — APPROVED** [review]

**Pull request merged**
