### PR TITLE
Add missing absorption lines

### PR DESCRIPTION
**Pull request by londumas**
Add missing absorption lines. Fixes issue https://github.com/igmhub/picca/issues/510/.
In the following plots, I give the stack of the delta in the different forests at the rest-frame of the DLAs.
In red you have the definition of the lower bound of the Lya and Lyb forests, in green the Lyman serries and in black the absorption lines. I added missing lines up to the CIV forest.

stack_0

stack_1

stack_2

### CODE REVIEW

**Comment by vserret** [comment]
@londumas Where did you fint the values for the atomic transitions ? 
I've found some different values on NIST

**Comment by londumas** [comment]
@vserret, Thanks for the review. I used http://adsabs.harvard.edu/abs/1991ApJS...77..119M, the same paper I used for the other transitions and I checked it worked on the DLA stack.

**Comment by vserret** [comment]
@londumas I think we have already had this conversation but would you mind to use NIST values ? I think these are the reference values

**Comment by londumas** [comment]
Setting this in the proper PR:

> @vserret, I hve little time to do that now. What we can do is merge this and add a issue ticket with this idea. Anyway, it has very little effect since it acts only on the decimals. Is that ok for you?

> @londumas I think you did not reply on the good PR. Anyway, you are right. The effect would be very very small. We can keep that for latter.

**Comment by londumas** [comment]
@vserret, then could you review the PR? Thanks a lot for the work.

**Pull request merged**
