### PR TITLE
Run hesse as option

### PR DESCRIPTION
**Pull request by londumas**
This PR adds the option to run hesse.
In MgII-correlations, I get basically the same best fits and best errors but not the same correlation coefficients if I start far or near the minimum.
This is fixed by running hesse at the end of calculation.

- no hesse, near minimum: `cor[drp, bias_MgII(2796)] 49.3324951424`
- no hesse, far from minimum: `cor[drp, bias_MgII(2796)] 56.2345843166`
- with hesse, near minimum: `cor[drp, bias_MgII(2796)] 56.5666886943`
- with hesse, far from minimum: `cor[drp, bias_MgII(2796)] 56.5175449217`

### CODE REVIEW

**Comment by ngbusca** [comment]
@londumas how do you modify which `.ini` file to read the `hess` option?

**Comment by londumas** [comment]
Following `verbosity`, you add the following. Does that work for you?
```
[hesse]
level = 1
```

**Comment by londumas** [comment]
@ngbusca, could you review?

**Comment by ngbusca** [comment]
@londumas I'll let you merge whenever it's ready

**Pull request merged**
