### PR TITLE
look if some bins are empty

### PR DESCRIPTION
**Pull request by londumas**
Fixes issue https://github.com/igmhub/picca/issues/274 by testing if some bins are empty.
If some are, print an error message and exit.
@ngbusca, run the unitest. Ready to be merged.

### CODE REVIEW

**Comment by londumas** [comment]
I can also move this test inside `picca.utils.smooth_cov`. What do you prefer?

**Comment by ngbusca** [comment]
@londumas let's add an option `--do-not-smooth` so people can still get a covariance out

**Comment by ngbusca** [comment]
@londumas I agree that it should be the smooth_cov function that complains if it can't smooth (so move the test there). Thanks!

**Comment by londumas** [comment]
@ngbusca, thanks for the review.
Ready to be merged.

**Comment by londumas** [comment]
@ngbusca, done

**Comment by londumas** [comment]
Sorry, made a mistake.

**Comment by londumas** [comment]
@ngbusca, done

**Pull request merged**
