### PR TITLE
Pblic data dr16

### PR DESCRIPTION
**Pull request by londumas**
This is near ready commit to add the public data of the DR16 results.
Of course I do not put the data yet, they are on the svn, but I updated the readme.
@andreufont coud you do  review ?
@andreicuceu could you tell me what files are needed for COSMO-MC ?
I think it would be nice to add them there. What do you think ?

### CODE REVIEW

**Comment by londumas** [comment]
@andreufont, to do the review the best is to have a look at what the new redme looks like.

**Comment by andreufont** [comment]
Hi @londumas - I took a look at the README file, and it looks great. I also tested the plotting script for DR14, the instructions are very clear.

**Comment by andreufont** [comment]
Yes, it would be great to add an update for both CosmoMC and MontePython. I believe these are done by contacting the developers and providing them with the new files, I'm not sure we can do it here.

**Comment by londumas** [comment]
@andreufont, do you know who uses `MontePython`? I know for CosmoMC.

**Comment by andreufont** [comment]
Hi @londumas - do you know anyone who has used our CosmoMC module? I know that at least the group by Julien Lesgourgues has used the the MontePython module, for thier studies of H_0 from BAO+BBN. 

MontePython is python, while CosmoMC is fortran, and specially those that use CLASS instead of CAMB tend to use MontePython, I believe.

**Comment by andreufont** [comment]
Also, it is very easy to do both, Andrei / Pablo / James know how to do it, so I would just do both.

**Comment by londumas** [comment]
@andreufont, I just send an email to that person.

**Comment by andreufont** [comment]
Yes, you are right, now we use it internally in eBOSS. Good call!
________________________________

**Pull request merged**
