### PR TITLE
Add chi2scan to fitter2

### PR DESCRIPTION
**Pull request by londumas**
Add computing chi2 scan in fitter2.
The current version is not ready to be merged.
The results are not stored.
@ngbusca, this PR is not the most beautiful one, but it does the job. Don't hesitate if you want changes.
Also could you tell me the best way to store the data?

### CODE REVIEW

**Comment by ngbusca** [comment]
@londumas it doesn't look like your local master is in sync with the remote, despite your last commit. Can you double check?

**Comment by londumas** [comment]
@ngbusca, it seems to be. How can you say this?

**Comment by londumas** [comment]
@ngbusca, The current PR does everything.
It can compute a 1d or 2d chi2 scan, depending on the number of entries in the `[chi2 scan]` section.
It stores the results in a group `chi2 scan/result`. This subgroup has attributes with values are the index of the arrays. Its value `chi2 scan/result/values.value` gives the array with all the best fit

**Comment by ngbusca** [comment]
It's ok now!

**Comment by londumas** [comment]
Here is the chi2 scan for ap in Lya-QSO correlation.
ap_scan

**Comment by londumas** [comment]
Here is the same in 2d for ap,at.
@ngbusca, ready to be merged. If you want some changes in parameters names or group or subgroup, don't hesitate.
ap_at_scan

**Comment by ngbusca** [comment]
@londumas can you merge with master to check the automatic travis tests?

**Pull request merged**
