### PR TITLE
Fix xcf

### PR DESCRIPTION
**Pull request by iprafols**
Some fixes to be able to run xcf with daily data

### CODE REVIEW

**Review by Waelthus — APPROVED** [review]
This looks allright. For some reason all tests are failing though.

**Comment by iprafols** [comment]
same reason as the others: the updated libraries

**Comment by Waelthus** [comment]
It looks like it's an issue of LAST_NIGHT vs LASTNIGHT:
```self = <TableColumns names=('TARGETID','Z','RA','DEC','DESI_TARGET','SV1_DESI_TARGET','SV3_DESI_TARGET','TILEID','PETAL_LOC','NIGHT','SURVEY','HEALPIX')>
item = 'LASTNIGHT'
    def __getitem__(self, item):
        """Get items from a TableColumns object.
        ::
          tc = TableColumns(cols=[Column(name='a'), Column(name='b'), Column(name='c')])
          tc['a']  # Column('a')
          tc[1] # Column('b')
          tc['a', 'b'] # <TableColumns names=('a', 'b')>
          tc[1:3] # <TableColumns names=('b', 'c')>
        """
        if isinstance(item, str):
>           return OrderedDict.__getitem__(self, item)
E           KeyError: 'LASTNIGHT'
```

and similar error messages are in the logs...

**Comment by Waelthus** [comment]
Re updated libraries I just started running the github-action on master again. If any test issues are purely from updated libs, those tests should fail now (as results would be changed).

**Comment by iprafols** [comment]
My bad, I had indeed missed some changes

**Pull request merged**
