### PR TITLE
Save errors on eta and vlss

### PR DESCRIPTION
**Pull request by mblomqvist**
Extract the errors on the parameters eta and vlss and save to the output fits file. Tested on subsamples of Lya and CIV spectra.

### CODE REVIEW

**Comment by ngbusca** [comment]
@mblomqvist the code looks good. Do the errors make sense ?

**Comment by mblomqvist** [comment]
Here are the results for 10,000 CIV spectra. Errors are small but seem reasonable at least in a relative sense.
eta_civ
vlss_civ

**Comment by londumas** [comment]
how does it compare to sub-sampling errors by dividing the ~300,000 CIV forests into ~100 samples ?

**Comment by mblomqvist** [comment]
Actually, the errors seem rather small compared to what was derived using my own code on the full data set. Is there a particular reason why iminuit would estimate unreliable errors?

**Comment by londumas** [comment]
yes, I think if the chi2 isn't defined well enough. For example if it doesn't take care of the correlation between pixels. Did you have a look at the result of the subsampling errors ?

**Comment by mblomqvist** [comment]
No, I haven't looked at the scatter from subsampling. Feel free to have a crack at it. Since eta and vlss are quantities derived from the data that are applied to calculate the pixel weights, it seemed reasonable to check how well they are determined. Igmhub isn't really the right forum to interpret the results.

**Comment by ngbusca** [comment]
@mblomqvist I agree with @londumas that if we want to add the uncertainties they should be meaningful. If you really want this change I'd suggest that you do a dedicated study on the chi2 of the eta and sigma_lls fits. In Busca et al (I think it's the only place where we showed uncertainties in these parameters) I calculated the uncertainties from the variance in the mocks....

**Comment by mblomqvist** [comment]
Meaningful errors are obviously important. You know better than I do what are the limitations of the picca implementation and iminuit. The fact of the matter is that Busca et al is the only place where eta and vlss have been presented, which was a long time ago for DR9 and 15 mocks. An update of the results would be useful at some point.

**Pull request closed without merging**
