### PR TITLE
add DR16 public data

### PR DESCRIPTION
**Pull request by londumas**
add DR16 public data, update the data/README.md and update the plot for data with DR16 scans.
Also updates the packages in the requirements to latest releases, except for iminuit where they have a small bug with minos:
https://github.com/scikit-hep/iminuit/issues/458
The arxiv id of the DR16 paper will be updated once known on Monday in another PR.

Ready to be merged.

### CODE REVIEW

**Comment by londumas** [comment]
@andreufont, do you want to finish the new line addition or to you want me to take over?
Thansk for the review

**Comment by andreufont** [comment]
HI Helion,

I just finished it. I'd like to try running the python script on the new data file, if you don't mind. I'll try it now.

By the way, do you want this to be part of the actual DR16 release of Picca? You have a pre-release from July 2019, but I'm not sure whether you wanted that one or the new master to be the official release of DR16.

Cheers,
Andreu
________________________________

**Comment by londumas** [comment]
> It would be good to clarify the pre-release / release situation, but we can do that separately.

Good idea, let me do that

**Comment by londumas** [comment]
@andreufont, I just added the papers status either submited or published.
Does that work for you ?

**Comment by andreufont** [comment]
Sorry I wasn't clear. These changes are good, but that's not what I meant. 

In July 2019 you created a tag for Picca, Theodebert-DR16-alpha (also known as v4.alpha), that was supposed to be the stable version of Picca to reproduce the DR16 results. However, this was a "pre-release", not a full release (not sure what the differences are). And more importantly, the README and the data to use the DR16 results are now in the master branch, but not in that release that you created last year.

So how should we proceed?
 - Should we tag the current master as the DR16 official release of Picca? Several things have changed in Picca during the last year, but I recently checked that indeed we recover the DR16 results.
 - Should we instead make that pre-release (v4.alpha) the official DR16 release? In that case, we should document well that even though the v4 is the official release to reproduce the DR16 results, the actual data files from DR16 are not in that release.

**Comment by londumas** [comment]
@andreufont, both work for me, I think all the changes were benign and as you said verified by you. I leave you decide.

**Comment by andreufont** [comment]
Great. I've merged the PR, and moved the discussion on the DR16 to a different issue.

**Pull request merged**
