### PR TITLE
Remove non-ASCII characters in headers of sky masks

### PR DESCRIPTION
**Pull request by andreufont**

### CODE REVIEW

**Comment by andreufont** [comment]
Hi @ngbusca , @londumas , @julienguy , @vserret  - do you know who has access to merge pull requests?

This is a very small and trivial change that would make our life easier if it was approved, otherwise python complains about non-ASCII characters in headers.

Thanks!

**Comment by londumas** [comment]
@andreufont, done

**Comment by andreufont** [comment]
Thanks @londumas!

Should we add new people in the list of authorised users? I would be happy to be added.

**Comment by londumas** [comment]
@andreufont, this is done. https://github.com/orgs/igmhub/people. You are now a owner.
However use that with caution, e.g. each PR should be precedeed by a bug report to explain what is the issue, and there should always have at least a few senteces explaining the PR. Also each PR should be reviviwed before.

**Comment by andreufont** [comment]
Great. Thank you very much, I'll be cautious with PRs.

**Pull request merged**
