### PR TITLE
allow fitter2 to read bash variable

### PR DESCRIPTION
**Pull request by londumas**
Add expansion of bash variables.
Tested and works

### CODE REVIEW

**Comment by ngbusca** [comment]
@londumas can you provide an example of what this does?

**Comment by londumas** [comment]
@ngbusca, it will read such a file. Without this PR, it will be unable to understand `$PICCA`
```
[data sets]
ini files = $HOME/Articles/mgII/Work/Data/Correlations_rmin_0_rmax_200/Individual/QSO/QSO__LYA_in_LYA/config.ini

[fiducial]
filename = $PICCA/py/picca/fitter2/models/PlanckDR12/PlanckDR12.fits

[output]
filename = $HOME/Articles/mgII/Work/Data/Correlations_rmin_0_rmax_200/Individual/QSO/QSO__LYA_in_LYA/result.h5
```

**Comment by londumas** [comment]
@ngbusca, added correcting bugs in Python3. It works also in Python2

**Comment by ngbusca** [comment]
@londumas I agree that this is a very useful addition, thanks for implementing this. This goes towards resolving issue #314 

But you've also secretly fixed the print problem in io.py :P ! It's great to fix problems, but please mention them in the description of the PR! I've independently fixed io.py on master (before noticing your fixes), and this generated conflicts in the branch. Could you please resolve them?

**Comment by londumas** [comment]
@ngbusca, sorry I should have done it in a seperate PR. Ready to be merged.

**Comment by londumas** [comment]
Fix issue https://github.com/igmhub/picca/issues/314

**Comment by londumas** [comment]
@ngbusca, ready to be merged

**Pull request merged**
