### PR TITLE
force print fastMC

### PR DESCRIPTION
**Pull request by londumas**
This PR adds forcing fastMC to print the steps of the calculation to better track it

### CODE REVIEW

**Comment by ngbusca** [comment]
what's the problem with the current `print`?

**Comment by londumas** [comment]
The issue with `print` is that when running `fitter2 chi2.ini > send.txt &`, it really prints only when the printing memory is full. Then it is not easy to keep track at what step the calculation is at.

**Comment by mblomqvist** [comment]
@londumas Does the same issue affect the parameter scan print output too? If so, could you change it too?

**Comment by londumas** [comment]
@mblomqvist, done.

**Comment by ngbusca** [comment]
all this `sys/print` conundrum comes about because we want to keep python2 compatibility... eventually (in python >= 3.6) we should use systematically `print(...,flush=True)`. Let's go with Hélion's solution for now... @londumas anything else you want to change before merging?

**Comment by londumas** [comment]
@ngbusca, makes sense. `print(...,flush=True)` sounds better.
Ready to be merged.

**Comment by ngbusca** [comment]
@londumas can you check if you can merge yourself? Don't forget to erase the branch

**Pull request merged**
