### PR TITLE
hcds in cross correlation (addresses issue #332)

### PR DESCRIPTION
**Pull request by ngbusca**
This PR adds the HCDs model to the cross correlation. It also allows to combine any Pk model with any velocity dispersion model.

This implies a change in the `cross.ini [model]` section:
    [model]
    model-pk = pk_hcd_cross
    velocity dispersion = pk_velo_lorentz

### CODE REVIEW

**Comment by ngbusca** [comment]
I have also renamed `lls` to `hcd`, so parameters in .ini files need to be updated accordingly (@vserret )

**Comment by ngbusca** [comment]
I feel uneasy adding a UV model for the cross, I don't think there's a model that's supported by the literature.

**Comment by mblomqvist** [comment]
@ngbusca We should discuss the generality of the UV model with the experts. For now, we are unable to reproduce the fit model of the DR12 cross paper which included UV.

**Comment by londumas** [comment]
@ngbusca, how does it work for metals and `velocity dispersion`now?

**Comment by ngbusca** [comment]
@mblomqvist I think we didn't give it enough thought in DR12. We can always reproduce the DR12 fits by checking out the DR12 tagged version and using fitter1.

@londumas currently we can't include these factors in the metal P(k) (but we probably should)

**Pull request merged**
