### PR TITLE
Resolve issue 399

### PR DESCRIPTION
**Pull request by vserret**
These are the results for the lya auto fit with the old version of do_metal_dmat.py : 
L0_hcd = 14.247 +/- 0.449
ap = 1.035 +/- 0.039
at = 0.987 +/- 0.048
beta_LYA = 1.529 +/- 0.106
beta_hcd = 0.678 +/- 0.174
bias_LYA = -0.200 +/- 0.006
bias_SiII(1190) = -0.002 +/- 0.000
bias_SiII(1193) = -0.001 +/- 0.000
bias_SiII(1260) = -0.001 +/- 0.000
bias_SiIII(1207) = -0.004 +/- 0.000
bias_gamma = 0.025 +/- 0.063
bias_hcd = -0.034 +/- 0.004
chi2 = 1548.11, ndata = 1590, npar = 12
chi2/DOF = 1548.11/1590-12
p = 0.700

With this version of the code : 
L0_hcd = 14.252 +/- 0.451
ap = 1.035 +/- 0.039
at = 0.987 +/- 0.048
beta_LYA = 1.533 +/- 0.107
beta_hcd = 0.675 +/- 0.174
bias_LYA = -0.200 +/- 0.006
bias_SiII(1190) = -0.003 +/- 0.001
bias_SiII(1193) = -0.002 +/- 0.001
bias_SiII(1260) = -0.001 +/- 0.001
bias_SiIII(1207) = -0.007 +/- 0.001
bias_gamma = 0.021 +/- 0.063
bias_hcd = -0.034 +/- 0.004
chi2 = 1548.27, ndata = 1590, npar = 12
chi2/DOF = 1548.27/1590-12
p = 0.699

Note : I've corrected a bug in the old version, see l.375 in the old or 397 in the new.

### CODE REVIEW

**Comment by londumas** [comment]
@vserret, could you merge with master, correct conflicts and produce again your `*fits.gz` files?
To merge with master:
```
merge master
git push
```

**Comment by ngbusca** [comment]
@vserret I've implemented both your changes from this PR and PR #401. Could you double check? Indeed, it was a bug, and it wasn't the only one of its kind.

I've also slightly simplified (I think) the logic of `do_met_dmat` but it would be good if you could verify it as well.

**Comment by vserret** [comment]
ok for me

**Comment by ngbusca** [comment]
@vserret you have to approve ;^)

**Comment by vserret** [comment]
I can't 
they said "pull request authors can't approve their own pull request"

**Comment by ngbusca** [comment]
Ok, I'll approve (on your behalf!). Did you check that the changes from PR #401 are also correctly implemented? If yes, I'll close PR #401 as well.

**Comment by vserret** [comment]
Yes, seems good for me 
You can close PR#401

**Pull request merged**
