### PR TITLE
fix issue 257

### PR DESCRIPTION
**Pull request by londumas**
fix https://github.com/igmhub/picca/issues/257
Loosing pairs because of definition of angmax with forest-forest cross-correlation

### CODE REVIEW

**Comment by londumas** [comment]
@ngbusca, I don't see any. Where ?

**Comment by ngbusca** [comment]
@londumas you are right, there are no tabs. Before merging, have you checked that this bug is not present in other places?

**Comment by londumas** [comment]
@ngbusca, I corrected in do_cf, do_dmat and do_metal_dmat.
Should I look elswhere for forest1-forest2 correlation ?

**Comment by ngbusca** [comment]
@londumas I was thinking the xcf files

**Comment by londumas** [comment]
no the xcf files are ok.
See https://github.com/igmhub/picca/search?utf8=%E2%9C%93&q=angmax&type=

**Pull request merged**
