### PR TITLE
Refactor diff

### PR DESCRIPTION
**Pull request by ngbusca**
The  fact that the diff field does not get coadded over multiple observations was causing a crash when reading from spplates. I have refactored the diff and reso fields such that they stay None as the default value. This avoids the crash but I don't know if it breaks something on the Pk1D side (it doesn't break the unittests).

### CODE REVIEW

**Comment by ngbusca** [comment]
@Cyeche can you try this branch on a realistic Pk1D analysis?

**Comment by londumas** [comment]
@ngbusca, I feel incompetent to review this PR.

**Comment by Cyeche** [comment]
Ok it doesn’t break the true data...

> 
> @Cyeche <https://github.com/cyeche> can you try this branch on a realistic Pk1D analysis?

**Comment by ngbusca** [comment]
Thanks @Cyeche

**Pull request merged**
