### PR TITLE
removed squares from sinc

### PR DESCRIPTION
**Pull request by ngbusca**
This branch fixes issue #376 reported by @vserret (thanks!). I've only removed the squares form the sinc functions as originally suggested by @vserret . The motivation can be found in the photo of my blackboard posted on the issue. It would be good if other people double-check the math.

### CODE REVIEW

**Comment by londumas** [comment]
@ngbusca, you have to reproduce the h5py file.

**Comment by londumas** [comment]
Could we imagine a simple test of this ? It should be simple.
Let's fill the auto-correlation with the power-spectrum where beta = 0 and bias = 1, on a 4x4 grid and fit it with picca. Then do the same with a grid 10x10 and 1x1. what do you think ?

**Comment by ngbusca** [comment]
@londumas can you remind me how to regenerate the test reference files?

**Comment by londumas** [comment]
@ngbusca, in `test/test_cor.py` change the boolean and the value of on attribute:
```
 self._test = False
self._branchFiles = './new_data/'
```
create the './new_data/' directory, run the test and then copy the new file to `data/`.

**Pull request merged**
