### PR TITLE
Modifications to do_cf and do_xcf as per issues 289 and 290

### PR DESCRIPTION
**Pull request by jfarr03**
Addresses the issues described in #289 and #290.

Also fixes a very minor issue discovered in py/picca/data.py: the project function defined in line 419 would cause NaN errors when running do_cf if a skewer contained only 1 cell with IVAR>0.

### CODE REVIEW

**Comment by ngbusca** [comment]
Thanks for implementing this @jfarr03. Could you merge your branch with master:

    git checkout master
    git pull
    git checkout from_image_adjustments
    git merge master

so that travis runs the automatic tests? They should be meaningful now...

**Comment by ngbusca** [comment]
@jfarr03 you will also have to `git push origin from_image_adjustments` after the last merge

**Comment by ngbusca** [comment]
@jfarr03 your tests are failing. You can also run them locally to try to debug: `python py/picca/test/test_cor.py`

**Comment by ngbusca** [comment]
@jfarr03 it's not just a matter of running the code, there are checks to make sure that the proposed code does not change the results of standard analyses.

**Comment by jfarr03** [comment]
Sure that makes sense - the tests didn't run on my local machine but the in-browser ones now seem to have passed. The issue locally was coming from my version of Python, though, rather than anything in the picca code, so I don't think it's anything to worry about!

The interplay between --in-dir and --from-image is now as follows:

 - if just '--in-dir {directory name}' is specified, then everything works as before. This can only accept one directory or one file (.fits or .fits.gz) as an input
 - if '--from-image' is specified with no argument, then the from image option is followed using the argument of '--in-dir'. This is how I was using it previously
 - if '--from-image {directory name}' is specified, then the from image option is followed using the argument of '--from-image', and the argument of '--in-dir' is ignored. This can accept multiple directories or files as an input

Ideally it'd be great to make '--in-dir' able to accept multiple directories or files, so then '--from-image' could return to just being a flag, but that would require more work to check it doesn't cause any problems elsewhere, so I understand that you're not keen on changing '--in-dir' at the moment. Let me know if there's anything you think needs more work!

**Pull request merged**
