### PR TITLE
Pk1 d

### PR DESCRIPTION
**Pull request by ngbusca**
I'm trying this PR again since the previous had many problems with git that I don't understand.  Sorry @londumas, can you take a look again?

### CODE REVIEW

**Comment by ngbusca** [comment]
@Cyeche I've made some changes to make the code run in python3 and removed the dependency of fftw (replaced by scipy.fftpack.fft). It passes the automatic tests (so the new fft behaves just like the old one) but it would be good to check on data.

**Comment by ngbusca** [comment]
@Cyeche @nathalieGit could you review this branch? Thanks!

**Comment by Cyeche** [comment]
I checked it, it is OK.

I have an additional comment about test_cor for Pk1D (spec and pix format) Il will send it in another mail.

**Comment by ngbusca** [comment]
Thanks @Cyeche !

**Pull request merged**
