### PR TITLE
Redo dr12

### PR DESCRIPTION
**Pull request by andreufont**
I've done a couple of minor changes to be able to redo DR12 and DR14 analyses:
 - add option to keep objects with non-positive THING_ID, since this was done in du Mas des Bourboux et al. (2017).
 - ignore DLAs in DLA catalog if there is no quasar with same THING_ID in quasar catalog (19 objects in one of the DR14 DLA catalogs are not in the DR14 quasar catalog).

### CODE REVIEW

**Comment by andreufont** [comment]
I'm not passing the codacy test, because with the addition of one extra argument the function is now considered to be "too complex". 
I agree that shorter argument lists are better, but it is not the fault of this very simple commit, so I'd say we should go ahead and accept the pull request as is.

**Comment by londumas** [comment]
@andreufont, I am in favor of not merging this issue.
It is adding too many if and conditions to a already complicated io.
Even Codacy said enough with too much complication.
You can keep this branch unmerged for record.
But you decide.

**Comment by andreufont** [comment]
I think it would nice to have the option to reproduce the DR12 results. I noticed that there is an old branch named keep_zero_thid hta was trying to do the same, but it was never merged either.

**Comment by andreufont** [comment]
Ok, I've been convinced by Helion. We'll keep this branch alive but unmerged, in case others want to reproduce DR12 results with Picca.

**Pull request closed without merging**
