### PR TITLE
read TARGET_RA and TARGET_DEC

### PR DESCRIPTION
**Pull request by londumas**
read TARGET_RA and TARGET_DEC

### CODE REVIEW

**Comment by ngbusca** [comment]
This is not a bug!! The datamodel from desispec changed.

**Comment by londumas** [comment]
@ngbusca, ok. Changed to "enhancement".

**Comment by londumas** [comment]
@ngbusca, I made the changes. Could you review?

**Comment by londumas** [comment]
@ngbusca, could you review the changes?

**Comment by ngbusca** [comment]
@londumas you didn't address the requested changes

**Comment by londumas** [comment]
@ngbusca, I did but it had not registered.
I changed the way of getting the column names with the `get_colnames` method.
Could you tell me if it is ok?

**Pull request merged**
