### PR TITLE
Fix missing pairs from wrong assigned healpix

### PR DESCRIPTION
**Pull request by londumas**
Fix missing pairs from wrong assigned healpix, in shuffled.
Fix ticket https://github.com/igmhub/picca/issues/651

### CODE REVIEW

**Comment by joselotl** [comment]
The fix works for me. It assigns correctly the healpix pixels.

**Comment by londumas** [comment]
@joselotl, perfect. Can you do the review?

**Comment by londumas** [comment]
Here is the ratio of number of pairs, for the cross-correlation and its equivalent shuffled: 
`--shuffle-distrib-obj-seed`
cross

```
import matplotlib.pyplot as plt
import fitsio
h1 = fitsio.FITS('../../../Correlations/xcf_z_0_10.fits.gz')
h2 = fitsio.FITS('xcf_z_0_10.fits.gz')
plt.plot(h2[1]['NB'][:]/h1[1]['NB'][:])
plt.xlabel('bin index')
plt.ylabel('nb ration')
plt.title('cross')
plt.grid()
plt.show()
```

**Comment by londumas** [comment]
@joselotl, can you post a similar plot for your 3pcf? I am computing right now for the auto.

**Comment by londumas** [comment]
@joselotl, so now, thanks to you, the mean ratio of number of pairs is indeed correct and equal to 1, however because of the 3d clustering of quasars, it is not exactly 1 for all bins. Hence, what I said by email still stands: to get the estimated variance, in each bin, you have to correct by the ratio of number of pairs.

**Comment by joselotl** [comment]
Here is the ratio for the 3pcf. In this case corresponding to the number of triangles per bin. It is also close to one but not excactly

image

**Comment by londumas** [comment]
Simply to keep track, here is the ratio for the cross, when using `--shuffle-distrib-forest-seed`.

cross_different

**Comment by londumas** [comment]
@joselotl, thanks for catching this issue.

**Pull request merged**
