### PR TITLE
Remove trailing whitspace

### PR DESCRIPTION
**Pull request by londumas**
Step toward applying all recommendation of Codacy: removing all trailing spaces.
https://github.com/igmhub/picca/issues/369

### CODE REVIEW

**Comment by londumas** [comment]
@ngbusca, ready to be merged.

**Comment by ngbusca** [comment]
@londumas can you resolve the conflicts?

**Comment by ngbusca** [comment]
@londumas is it ready to be merged?

**Comment by londumas** [comment]
@ngbusca, it is.

**Pull request merged**
