### PR TITLE
Cut zqso

### PR DESCRIPTION
**Pull request by vserret**
do a cut in zqso pairs during the computation of the cf

### CODE REVIEW

**Comment by vserret** [comment]
@ngbusca : the test is ok. This can be merged

**Comment by londumas** [comment]
@ngbusca, ready to be merged. @vserret ran the tests and it works

**Comment by mblomqvist** [comment]
This pull request was never merged. Why was it closed?

**Comment by ngbusca** [comment]
@mblomqvist after discussion (with you!) we realized that cutting on zqso_pair puts the lyb forest in the high-z bin while it's mostly low-z bins. @vserret is changing that to a cut on the redshift of the last forest bin which will fix it. It will be implemented for the cross as well...

**Comment by vserret** [comment]
@mblomqvist as @ngbusca said I'm changing the zcut. I will put the new version in few hours on git

**Comment by mblomqvist** [comment]
OK, very good.

**Pull request closed without merging**
