### PR TITLE
fix issue 232

### PR DESCRIPTION
**Pull request by londumas**
add errors of eta, var_lss, fudge
https://github.com/igmhub/picca/issues/232

### CODE REVIEW

**Comment by mblomqvist** [comment]
This is the same modifications I proposed a few weeks ago...

**Comment by ngbusca** [comment]
Isn't this exactly what @mblomqvist added a few weeks ago? If you guys want this option, that's fine with me, but It would be good to take the chance to study a bit the errors, not just add blindly what minuit reports. @mblomqvist what do you think?

**Comment by londumas** [comment]
I added a hess calculation, it gives very different results than the minos one.
Also it is important to remove bins where the fit failed when plotting.

**Comment by londumas** [comment]
@ngbusca, I agree. But studying the error isn't a part of picca.

**Comment by ngbusca** [comment]
@londumas if picca reports an error the burden is on picca to make sure it's not senseless...

**Comment by ngbusca** [comment]
@londumas otherwise it's very simple, we just return random numbers for everything.

**Comment by londumas** [comment]
@ngbusca, the code gives the minos error. A user could decide to see the sub-samples errors.
This is up to him, the code will not give this to him.
I imagine you would like me to compare these two types of errors.
Am I right ?

**Comment by ngbusca** [comment]
@londumas The first question is whether the chi^2 values are good. If they aren't, I wouldn't trust any estimation (Minuit, Hess, Minos...). So it would be great to look at subsamples and compare the errors from subsample to what minuit reports ( I wouldn't include minos or hesse since they are less stable and we don't want that to crash).

Once we have a good idea of how the subsample errors compare to minuit, then we just add a cautionary note on the README. But we need to do this study.  If you don't want to/can't do it and @mblomqvist agrees to add this, then I'll just merge.

**Comment by ngbusca** [comment]
What I don't understand is that you want to include this option, but don't want to/don't have time (etc). do the study. This means that you don't really need the errors on these parameters, so why bother adding that to the code? I know it's easy, but there are better ways to use your time ;^)

**Comment by londumas** [comment]
@ngbusca, I don't need the error on the parameters, however I need to remove bins where the fit failed.
That is why I did this commit. For the part where I have:
```
+            eta[i] = 1.
+            vlss[i] = 0.1
+            fudge[i] = 1.*fudge_ref
+            err_eta[i] = 0.
+            err_vlss[i] = 0.
+            err_fudge[i] = 0.
```

**Comment by londumas** [comment]
So what about merging this and adding an issue to picca in order to study this error, and give cautions if need be into README.md.

**Comment by ngbusca** [comment]
I wan't to hear also from @mblomqvist

**Comment by mblomqvist** [comment]
If one wants to show a plot of eta(z) or vlss(z) in a paper, having reasonable error bars is important. I assumed that they were, but understood from your comments that they might not be. I guess I have a mild preference for adding the errors to the output file, but agree that they need to be studied.

**Comment by ngbusca** [comment]
I'm actually leaning towards not having them. This way, the next person who actually "needs" them will have to do the study (and then we can put them in in a well understood way). Otherwise, she might just blame the eta/vlss errors on picca and move on.

**Comment by mblomqvist** [comment]
Fair enough.

**Comment by londumas** [comment]
ok, then just let me leave the part that does:
```
+            eta[i] = 1.
+            vlss[i] = 0.1
+            fudge[i] = 1.*fudge_ref
```
this is useful to remove bins where the fit failed

**Comment by ngbusca** [comment]
@londumas ok, I'll take a look

**Comment by londumas** [comment]
@ngbusca, just tested this version, and it works.

**Comment by londumas** [comment]
ok to merge ? or want some changes ?

**Pull request merged**
