### PR TITLE
fix issue 276

### PR DESCRIPTION
**Pull request by londumas**
fix issue https://github.com/igmhub/picca/issues/276
"cpu_count()/2" breaks in Python3

### CODE REVIEW

**Comment by londumas** [comment]
@ngbusca, I looked at all the files except fitter/* and fitter2/*
I think I have all of the integer division.
Could you review the changes? You know more about the code of distortion matrix than I do.

**Comment by ngbusca** [comment]
@londumas I originally did ncpu = cpu_count()/2 to avoid a seeming loss of performance in a hyperthreaded system I was using at some point. It might be better to move back to ncpu = cpu_count(). Could you run a test to see if we gain from moving to ncpu = cpu_count() instead? If you do the test, remember to set OMP_NUM_THREADS = 1.

**Comment by londumas** [comment]
I guess for some reason `cpu_count()//2` is better. Strange...

`cpu_count()//2`:
```
time do_xcf.py --drq ~/Data/Catalogs/DR14Q_v3_1__THINGID_DR7.fits --out test.fits.gz --in-dir ../DR14/Delta_LYA/Delta/ --nspec 10000
real	1m36.582s
user	11m51.582s
sys	0m17.093s
```

`cpu_count()`:
```
time do_xcf.py --drq ~/Data/Catalogs/DR14Q_v3_1__THINGID_DR7.fits --out test.fits.gz --in-dir ../DR14/Delta_LYA/Delta/ --nspec 10000
real	1m46.339s
user	18m2.361s
sys	0m36.166s
```

**Comment by londumas** [comment]
`cpu_count()//2:`
```
time do_xcf.py --drq ~/Data/Catalogs/DR14Q_v3_1__THINGID_DR7.fits --out test.fits.gz --in-dir ../DR14/Delta_LYA/Delta/ --nspec 100000
real	12m0.263s
user	105m45.716s
sys	1m6.701s
```

`cpu_count()`:
```
time do_xcf.py --drq ~/Data/Catalogs/DR14Q_v3_1__THINGID_DR7.fits --out test.fits.gz --in-dir ../DR14/Delta_LYA/Delta/ --nspec 100000
real	11m50.567s
user	186m5.642s
sys	4m5.905s
```

**Comment by ngbusca** [comment]
@londumas do you confirm that you did your runs with export OMP_NUM_THREADS=1 ?

**Comment by londumas** [comment]
@ngbusca, I do.

**Comment by londumas** [comment]
@ngbusca, please also review the other `//` fix. I am not 100% sure I did good. There are no crash, but it is not enough.

**Comment by ngbusca** [comment]
@londumas sure

**Comment by ngbusca** [comment]
@londumas I'd like to understand the cpu_count issue...

**Comment by londumas** [comment]
@ngbusca, I agree. I don't think I can help you more than this.
But I feel it is another issue than python2 `/` vs. python3. `/`

**Comment by ngbusca** [comment]
@londumas are you running picca under python 3?

**Comment by londumas** [comment]
@ngbusca, on both: Python3 on NERSC, to test all the DESI pipeline
Python2 in Utah.

**Comment by ngbusca** [comment]
that's great! Were any other tweaks necessary?

**Comment by londumas** [comment]
@ngbusca, a lot. I am slowly going there. Because I want to understand what "2to3" does.

**Pull request closed without merging**
