### PR TITLE
deprecated scipy objects changed to numpy

### PR DESCRIPTION
**Pull request by iprafols**
This is a fix on issue #680. Scipy was still used in fitter, fitter2 and the tutorials. I updated the project so that all remaining sp functions are native to scipy (and not in numpy), at least for now.

### CODE REVIEW

**Comment by andreufont** [comment]
HI @iprafols - could you fix the conflict? I guess I just introduced it in merging the other PR.

**Comment by iprafols** [comment]
Done

**Comment by andreufont** [comment]
Let's wait for Travis to finish, but I think we can merge quickly.

**Comment by iprafols** [comment]
@andreufont now that the tests have passed, can we merge?

**Review by andreufont — APPROVED** [review]
It looks good.

**Pull request merged**
