### PR TITLE
fix issue 174

### PR DESCRIPTION
**Pull request by londumas**
code indentation mixes tab and spaces
https://github.com/igmhub/picca/issues/174

Testing on full auto correlation and on full cross correlation

### CODE REVIEW

**Comment by londumas** [comment]
I am testing on the full auto and cross fit.
I reveiwed the changes, but it would be good if you could also have a look @ngbusca .
I tell you when testing is complete

**Comment by londumas** [comment]
gives the same result as master for cross fit and auto fit.
Ready to be merged

**Comment by ngbusca** [comment]
did you look at the wedges as well?

**Comment by londumas** [comment]
no, only to the chi2 and to the save.pars.
How could it be different if the both these files are the same ?

**Comment by ngbusca** [comment]
I don't know...

**Comment by ngbusca** [comment]
I meant the wedges as a means to verify the residuals.dat

**Comment by londumas** [comment]
I just look at the wedgies, and the output are the same.
I can't be absolutely sure there is no bug introduced, but at least no major ones.

**Pull request merged**
