### PR TITLE
Fitter2 BAO amplitude parameter

### PR DESCRIPTION
**Pull request by mblomqvist**
Add the BAO amplitude parameter bao_amp to fitter2. Unittest failed (also on the master branch) on my laptop, see issue #351

### CODE REVIEW

**Comment by ngbusca** [comment]
I think we'd need to include the bao_amp parameter in the corresponding .ini file in the unittests. @londumas can you comment?

**Comment by ngbusca** [comment]
@mblomqvist the failure here is not related to the ang_cf but to the fact that the unittest for fitter2 doesn't know the bao_amp parameter (is not listed in the right .ini file)

**Comment by mblomqvist** [comment]
Right, I didn't think about that.

**Comment by ngbusca** [comment]
I'll fix it on my end in a sec

**Comment by ngbusca** [comment]
I've added the bao_amp parameter to the test/config_cf.ini but that's not enough.  The test finds a new parameter that isn't in the reference file so it's not happy. We need @londumas to tell us what's the best way forward, maybe we need to regenerate the reference file?

**Comment by mblomqvist** [comment]
This pull request was supposed to be a trivial update but turned out to be head scratcher ;)

**Comment by londumas** [comment]
@ngbusca, You need to regenerate the result file.

**Comment by ngbusca** [comment]
@londumas can you do that directly on this PR? You are the unittest master ;^)

**Comment by londumas** [comment]
@ngbusca, @mblomqvist. It isn't hard. Just change line 51 by:
```
self._test = False
self._branchFiles = './keep_tests/'
```
and do a:
```
mkdir ./keep_tests/
```
run the unittest on your laptop and copy the new result to the data and commit.

**Comment by ngbusca** [comment]
Thanks @londumas. @mblomqvist I'll take care of that

**Comment by ngbusca** [comment]
@londumas do I need to add the line

    self._branchFiles = './keep_tests/'

after line 51?

**Comment by londumas** [comment]
@ngbusca, yes it allows to save the output to a given directory not to a random directory in `/tmp`

**Comment by ngbusca** [comment]
@londumas thanks, that worked perfect. Let's see if travis likes it.

**Comment by mblomqvist** [comment]
Thank you both for fixing it.

**Pull request merged**
