### PR TITLE
fix issue 245

### PR DESCRIPTION
**Pull request by londumas**
Remove useless neighs after computation to avoid memory leak.
https://github.com/igmhub/picca/issues/245

### CODE REVIEW

**Comment by londumas** [comment]
Tested and works perfectly

**Comment by ngbusca** [comment]
@londumas good idea to clean up variables that are not used anymore. Just out of curiosity, what's the difference between e.g. setattr(d,'neighs', None) and d.neighs = None ?

**Comment by ngbusca** [comment]
@londumas by the way, why did you tag this as s bug? There was nothing wrong with the previous code.

**Comment by londumas** [comment]
> @londumas good idea to clean up variables that are not used anymore. Just out of curiosity, what's the difference between e.g. setattr(d,'neighs', None) and d.neighs = None ?

There are no differences, the good thing with `setattr` is that we can get all variable with a dictionnary, as we do for do_xcf since delta are no longer use afet

> @londumas by the way, why did you tag this as s bug? There was nothing wrong with the previous code.

Because it made a memory leak that produces crass for some computation

**Comment by ngbusca** [comment]
@londumas I see your point but note that you can't have memory leaks in python (unlike c++) since the garbage collector will always release memory that is not pointed by anything. Your changes make the code more memory efficient!

**Comment by londumas** [comment]
Yes, it isn't really a memory leak in a C++ way.

**Pull request merged**
