### PR TITLE
Added metadata option

### PR DESCRIPTION
**Pull request by SamYoules**
Amended picca_deltas.py to include option to write metadata to a fits file. The metadata contains the continuum fitting parameters.

### CODE REVIEW

**Comment by julianbautista** [comment]
Have this been tested without Travis? Travis doesn't test this by default.  
Could you please try to generate a table and make sure it runs?

**Comment by julianbautista** [comment]
I ran a test with Stripe 82 data and it works well. You can find the results @ NERSC in:
/global/project/projectdirs/desi/users/bautista/lya/DR16_tutorial
and the table is metadata_lya.fits

**Review by julianbautista — APPROVED** [review]
I've tested the production of the metadata table and all works fine. 
I'm approving. Thanks Sam

**Comment by SamYoules** [comment]
Thanks Julian.

**Comment by SamYoules** [comment]
Thanks Julian.

**Pull request merged**
