### PR TITLE
fix issue 401

### PR DESCRIPTION
**Pull request by vserret**

### CODE REVIEW

**Comment by vserret** [comment]
@ngbusca ready to be merged

**Comment by ngbusca** [comment]
@londumas @mblomqvist this PR adds each `fast MC` realization of the data to the output file. Any objections/comments?

**Comment by mblomqvist** [comment]
@ngbusca no objections

**Comment by mblomqvist** [comment]
What is the status of this PR?

**Comment by ngbusca** [comment]
@mblomqvist merged ;^)

**Pull request merged**
