### PR TITLE
llvmlite==0.31.0 for python2

### PR DESCRIPTION
**Pull request by londumas**
llvmlite==0.31.0 for python2, because version 0.32.1 is not compatible with python2

### CODE REVIEW

**Comment by londumas** [comment]
@andreufont, this PR fixes the python2 dependencies problem with e.g. llvmlite.
Dependencies are starting to drop python2, and thus are breaking the travis tests for this version of python2. This PR fixes this issue by lisiting the required version of the dependancies for python2 is a separte file. This will allow to be up to date with the latests version for python3

**Comment by iprafols** [comment]
Don't you think it would be easier to just drop python2 support, as suggested in #688 ?

**Comment by londumas** [comment]
@iprafols, that is a way to drop python2. We keep track of the version of the package needed for python2 in requirements-python2, and move on by default for python3 using the simple requirements.txt

**Comment by andreufont** [comment]
I think I agree with @iprafols, I'd favor the option of dropping python2 altogether. If we don't do it now, we'll do it in a year from now, and meanwhile we'll have to keep using __future__ modules.

Do we know of anyone who has used the python2 version in the last year?

**Pull request merged**
